### ISSUE TITLE
Core IR project - longer paper available for "Treadmill Paper"

### ISSUE THREAD

**Issue by hsellik** [chauff/IN4325#2]
The PDF file for "Perceptions of the Effect of Fragmented Attention on Mobile Web Search Tasks" in [Core IR Project Section](https://github.com/chauff/IN4325/blob/master/projectCoreIR.md) is only 5 pages long.

There seems to be a longer 10-page version available. We discovered it too late. Hence we did not capture some important data in our test application that was mentioned in the longer version of the paper.

@chauff , would it be possible to update the paper link, so the students next year have a longer version of the paper available in the early stages of their work? (In case the same papers get used next year)

**Comment by chauff** [comment]
Thanks for pointing this out, I will update the link!
